<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Jellyfin.Plugin.RemoteLibrary</AssemblyName>
    <RootNamespace>Jellyfin.Plugin.RemoteLibrary</RootNamespace>
    <Version>1.0.2</Version>
    <PackageLicenseExpression>GPL-2.0-or-later</PackageLicenseExpression>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="12.1.0">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Jellyfin.Model" Version="12.1.0">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Web\config.html" />
    <EmbeddedResource Include="Web\integration.js" />
  </ItemGroup>
</Project>
